#!/bin/sh
set -e

if [ "$#" -le 2 ]; then
#    echo "Usage: command <project-name> <terraform-dir> <workspace>"
    echo "Usage: command <project-name> <workspace> <res#1> ... <res#n>"

    exit 1
fi

project=$1
workspace=$2
echo "project: $1"
echo "workspace: $2"

cd /
project_dir=$project:$workspace
mkdir -p "projects/$project_dir"
cp projects/main.tf "projects/$project_dir/main.tf"
cd "projects/$project_dir"

s3_state="$project-ptl-terraform-state"
terraform init -backend-config="bucket=$s3_state"
terraform workspace select "$workspace"
echo terraform destroy -auto-approve "${@: 2}";
