#!/bin/sh
set -e

if [ "$#" -le 2 ]; then
#    echo "Usage: command <project-name> <terraform-dir> <workspace>"
    echo "Usage: command <project-name> <workspace> <res#1> ... <res#n>"

    exit 1
fi

project=$1
echo "project: $1"
workspace=$2
echo "workspace: $2"
shift 2

project_dir=$project:$workspace
echo "project dir: $project_dir"
s3_state="$project-ptl-terraform-state"
echo "s3 bucket for state: $s3_state"

cd /
mkdir -p "projects/$project_dir"
cp projects/main.tf "projects/$project_dir/main.tf"
cd "projects/$project_dir"

terraform init -backend-config="bucket=$s3_state"
terraform workspace select "$workspace"
echo terraform destroy -auto-approve "$@";
