#!/bin/sh
set -e

if [ "$#" -le 2 ]; then
    echo "Usage: command <project-name> <workspace> <res#1> ... <res#n>"
    exit 1
fi

project=$1
echo "project: $1"
workspace=$2
echo "workspace: $2"
shift 2

project_dir=$project:$workspace
echo "project dir: $project_dir"
s3_state="$project-ptl-terraform-state"
echo "s3 bucket for state: $s3_state"

cd /
prj_base_path="/mnt/projects"
mkdir -p "$prj_base_path/$project_dir"
cp /main.tf "$prj_base_path/$project_dir/main.tf"
cd "$prj_base_path/$project_dir"

echo terraform init -backend-config="bucket=$s3_state"
terraform init -backend-config="bucket=$s3_state"

echo terraform workspace select "$workspace"
terraform workspace select "$workspace"

echo terraform destroy -auto-approve "$@"
terraform destroy -auto-approve "$@"
